//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIMSApplication.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class StudentInformationTable
    {
		
		[Display(Name ="Distric Code")]
		[Required(ErrorMessage = "This field is required")]
		[MaxLength(9)]
		public string District_Code { get; set; }

		[Display(Name = "School Year Date")]
		[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
		[Required(ErrorMessage = "This field is required")]
		//[MaxLength(10)]
		public System.DateTime? School_Year_Date { get; set; }

		[Display(Name = "Student Id")]
		[Required(ErrorMessage = "This field is required")]
		[MaxLength(10)]
		public string Student_Id { get; set; }

		[Display(Name = "Reporting Date")]
		[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
		[Required(ErrorMessage = "This field is required")]
		//[MaxLength(10)]
		public System.DateTime? Reporting_Date { get; set; }

		[Display(Name = "Category Set Code")]
		[Required(ErrorMessage = "This field is required")]
		[MaxLength(100)]
		public string Category_Set_code { get; set; }

		[Display(Name = "Measure type")]
		[Required(ErrorMessage = "This field is required")]
		[MaxLength(9)]
		public string Measure_type { get; set; }

		[Display(Name = "Act 16 Fund Category Code")]
		[Required(ErrorMessage = "This field is required")]
		public int Act16_fund_Category { get; set; }
    }
}
